const OK= 200;
const CREATED= 201;
const NO_CONTENT= 204;
const BAD_REQUEST= 400;
const UNAUTHORIZED= 401;
const FORBIDDEN= 403;
const NOT_FOUND= 404;
const METHOD_NOT_ALLOWED= 405;
const NOT_ACCEPTABLE= 406;
const CONFLICT= 409;
const UNSUPPORTED_MEDIA_TYPE= 415;
const INTERNAL_SERVER_ERROR= 500;


module.exports = {
    OK,
    CREATED,
    NO_CONTENT,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    NOT_ACCEPTABLE,
    CONFLICT,
    UNSUPPORTED_MEDIA_TYPE,
    INTERNAL_SERVER_ERROR,
}



