const OK = "OK";
const CREATED = "CREATED";
const NO_CONTENT = "NO CONTENT";
const BAD_REQUEST = "BAD REQUEST";
const UNAUTHORIZED = "UNAUTHORIZED";
const FORBIDDEN = "FORBIDDEN";
const NOT_FOUND = "NOT FOUND";
const METHOD_NOT_ALLOWED = "METHOD NOT ALLOWED";
const NOT_ACCEPTABLE = "NOT ACCEPTABLE";
const CONFLICT = "CONFLICT";
const UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY";
const UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED MEDIA TYPE";
const INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR";
const NAME_NOT_ACCEPTABLE = "NAME_NOT_ACCEPTABLE";
const VERIFY_TYPE_IMAGE= "THE IMAGE HAVE TO BE PNG OR JPG"

module.exports = {
  OK,
  CREATED,
  NO_CONTENT,
  BAD_REQUEST,
  UNAUTHORIZED,
  FORBIDDEN,
  NOT_FOUND,
  METHOD_NOT_ALLOWED,
  NOT_ACCEPTABLE,
  CONFLICT,
  UNPROCESSABLE_ENTITY,
  UNSUPPORTED_MEDIA_TYPE,
  INTERNAL_SERVER_ERROR,
  NAME_NOT_ACCEPTABLE,
};
  